GET http://localhost:3030/


###
POST http://localhost:3030/api/settings/users
Content-Type: application/json

{
      "email" : "test@test.uk.com",
      "name" : "Erik",
      "surName" : "Evans"
}


###
GET http://localhost:3030/api/v1/users