GET http://localhost:3030/

###
POST http://localhost:3030/api/v1/admin/users
Content-Type: application/json

{
      "email" : "test@test.uk.com",
      "name" : "Erik",
      "surName" : "Evans"
}
###
GET http://localhost:3030/api/v1/users

###
GET http://localhost:3030/test/error


###
POST http://localhost:3030/api/v1/login
Content-Type: application/json

{
      "email": "gabriel@test.uk.com"
}